# Generated by Django 3.2.9 on 2022-01-22 21:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestioneMenu', '0018_remove_piatto_tempototale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('idIngrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneMenu.ingrediente')),
            ],
            options={
                'verbose_name': 'Spesa',
                'verbose_name_plural': 'Spese',
            },
        ),
        migrations.CreateModel(
            name='Scorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitaAttuale', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantitaMinima', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('idIngrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneMenu.ingrediente')),
            ],
            options={
                'verbose_name': 'Scorta',
                'verbose_name_plural': 'Scorte',
            },
        ),
        migrations.CreateModel(
            name='Preparazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('idIngrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneMenu.ingrediente')),
            ],
            options={
                'verbose_name': 'Preparazione',
                'verbose_name_plural': 'Preparazioni',
            },
        ),
    ]
