# Generated by Django 3.2.9 on 2022-01-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMagazzino', '0004_auto_20220122_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparazione',
            name='idIngrediente',
        ),
        migrations.RemoveField(
            model_name='spesa',
            name='idIngrediente',
        ),
        migrations.AddField(
            model_name='preparazione',
            name='idScorta',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestioneMagazzino.scorta'),
        ),
        migrations.AddField(
            model_name='spesa',
            name='idScorta',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestioneMagazzino.scorta'),
        ),
    ]
