# Generated by Django 3.2.9 on 2022-01-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMagazzino', '0005_auto_20220123_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparazione',
            name='idScorta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestioneMagazzino.scorta'),
        ),
        migrations.AlterField(
            model_name='spesa',
            name='idScorta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestioneMagazzino.scorta'),
        ),
    ]
