# Generated by Django 3.2.9 on 2022-01-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fattoInCasa', models.BooleanField()),
            ],
            options={
                'db_table': 'Ingredienti',
            },
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tempoTotale', models.FloatField()),
                ('tempoPreparazione', models.FloatField()),
                ('tempoCottura', models.FloatField()),
            ],
            options={
                'db_table': 'Piatti',
            },
        ),
    ]
