# Generated by Django 3.2.9 on 2022-01-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingrediente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='piatto',
            table=None,
        ),
    ]
