# Generated by Django 3.2.9 on 2022-01-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0002_auto_20220110_1258'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingrediente',
            table='Ingredienti',
        ),
        migrations.AlterModelTable(
            name='piatto',
            table='Piatti',
        ),
    ]
