# Generated by Django 3.2.9 on 2022-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0002_auto_20220125_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='descrizione',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
