# Generated by Django 3.2.9 on 2022-01-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0003_auto_20220110_1300'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='piatto',
            table=None,
        ),
    ]
