# Generated by Django 3.2.9 on 2022-01-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0004_alter_piatto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='piatto',
            table='Piatti',
        ),
    ]
