# Generated by Django 3.2.9 on 2022-01-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0005_alter_piatto_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Piatto',
        ),
    ]
