# Generated by Django 3.2.9 on 2022-01-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0006_delete_piatto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tempoTotale', models.FloatField()),
                ('tempoPreparazione', models.FloatField()),
                ('tempoCottura', models.FloatField()),
            ],
            options={
                'db_table': 'Piatti',
            },
        ),
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredienti'},
        ),
        migrations.AlterModelTable(
            name='ingrediente',
            table=None,
        ),
    ]
