# Generated by Django 3.2.9 on 2022-01-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0007_auto_20220110_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piatto',
            options={'verbose_name': 'Piatto', 'verbose_name_plural': 'Piatti'},
        ),
        migrations.AlterModelTable(
            name='piatto',
            table=None,
        ),
    ]
