# Generated by Django 3.2.9 on 2022-01-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0008_auto_20220110_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Misura',
                'verbose_name_plural': 'Misure',
            },
        ),
        migrations.CreateModel(
            name='IngredientePiatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.FloatField()),
                ('idIngrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneMenu.ingrediente')),
                ('idMisura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneMenu.misura')),
                ('idPiatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneMenu.piatto')),
            ],
            options={
                'verbose_name': 'IngredientePiatto',
                'verbose_name_plural': 'IngredientiPiatti',
            },
        ),
    ]
