# Generated by Django 3.2.9 on 2022-01-12 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0009_ingredientepiatto_misura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piatto',
            name='tempoCottura',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='tempoPreparazione',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='tempoTotale',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
    ]
