# Generated by Django 3.2.9 on 2022-01-14 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0011_auto_20220113_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientepiatto',
            name='idMisura',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='idMisura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneMenu.misura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientepiatto',
            name='quantita',
            field=models.FloatField(verbose_name=django.core.validators.MinValueValidator(0)),
        ),
    ]
