# Generated by Django 3.2.9 on 2022-01-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0014_auto_20220114_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piatto',
            name='idCategoria',
            field=models.CharField(max_length=20),
        ),
    ]
