# Generated by Django 3.2.9 on 2022-01-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0015_alter_piatto_idcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piatto',
            name='idCategoria',
        ),
    ]
