# Generated by Django 3.2.9 on 2022-01-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0016_remove_piatto_idcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='piatto',
            name='idCategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneMenu.categoria'),
            preserve_default=False,
        ),
    ]
