# Generated by Django 3.2.9 on 2022-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0018_remove_piatto_tempototale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misura',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
