# Generated by Django 3.2.9 on 2022-01-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='uscitaAttuale',
        ),
        migrations.RemoveField(
            model_name='ordinetemporaneo',
            name='uscitaAttuale',
        ),
    ]
