# Generated by Django 3.2.9 on 2022-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0002_auto_20220125_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tavolo',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
