# Generated by Django 3.2.9 on 2022-01-16 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneMenu', '0018_remove_piatto_tempototale'),
        ('gestioneSala', '0002_auto_20220116_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenteordine',
            options={'verbose_name': 'ComponenteOrdine', 'verbose_name_plural': 'ComponentiOrdini'},
        ),
        migrations.CreateModel(
            name='ComponenteTemporaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('uscita', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('variazioni', models.CharField(max_length=100)),
                ('idOrdine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneSala.ordine')),
                ('idPiatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneMenu.piatto')),
            ],
            options={
                'verbose_name': 'ComponenteTemporaneo',
                'verbose_name_plural': 'ComponentiTemporanei',
            },
        ),
    ]
