# Generated by Django 3.2.9 on 2022-01-16 14:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0003_auto_20220116_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineTemporaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uscitaAttuale', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Stato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneSala.stato')),
                ('idTavolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneSala.tavolo')),
            ],
            options={
                'verbose_name': 'OrdineTemporaneo',
                'verbose_name_plural': 'OrdiniTemporanei',
            },
        ),
    ]
