# Generated by Django 3.2.9 on 2022-01-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0004_ordinetemporaneo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentetemporaneo',
            name='idOrdine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneSala.ordinetemporaneo'),
        ),
    ]
