# Generated by Django 3.2.9 on 2022-01-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0005_alter_componentetemporaneo_idordine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordine',
            old_name='Stato',
            new_name='stato',
        ),
        migrations.RenameField(
            model_name='ordinetemporaneo',
            old_name='Stato',
            new_name='stato',
        ),
    ]
