# Generated by Django 3.2.9 on 2022-01-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0006_auto_20220116_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tavolo',
            name='inGestione',
            field=models.BooleanField(default=False),
        ),
    ]
