# Generated by Django 3.2.9 on 2022-01-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0009_ordinetemporaneo_orario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='stato',
        ),
        migrations.AddField(
            model_name='componenteordine',
            name='stato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestioneSala.stato'),
        ),
        migrations.AddField(
            model_name='componentetemporaneo',
            name='stato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestioneSala.stato'),
        ),
    ]
