# Generated by Django 3.2.9 on 2022-01-22 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0010_auto_20220122_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenteordine',
            name='stato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneSala.stato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentetemporaneo',
            name='stato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneSala.stato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordine',
            name='orario',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordinetemporaneo',
            name='orario',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
