# Generated by Django 3.2.9 on 2022-01-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0012_remove_ordinetemporaneo_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenteordine',
            name='variazioni',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
