# Generated by Django 3.2.9 on 2022-01-24 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0013_alter_componenteordine_variazioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenteordine',
            name='priorita',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
