# Generated by Django 3.2.9 on 2022-01-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0014_componenteordine_priorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenteordine',
            name='permessoPreparazione',
            field=models.BooleanField(default=False),
        ),
    ]
