# Generated by Django 3.2.9 on 2022-01-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSala', '0015_componenteordine_permessopreparazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componenteordine',
            name='permessoPreparazione',
        ),
    ]
